[package]
name = "dazscripts/simplebinds"
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
    "README.md",
]

[dependencies]