[package]
name = "dazscripts/simplebinds"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = [
    "default.project.json",
    "src/simplebinds",
    "src/**",
    "LICENSE",
    "wally.toml",
    "README.md",
]

[dependencies]